### PR TITLE
use export view for remote

### PR DESCRIPTION
**Pull request by 3nids**

### CODE REVIEW

**Comment by haubourg** [comment]
Hi @3nids , it seems you missed to upgrade the version in /system/version_inserts.sql

**Comment by 3nids** [comment]
good catch, should be good now.
@sylvainbeo does the new test checks for the version inserted?

**Comment by sylvainbeo** [comment]
@3nids Not sure to well understand the question. You mean does the new test check if there is an UPDATE versoin in the delta ?

**Comment by 3nids** [comment]
the hardcoded version that is inserted in `system/versions_insert.sql`

**Comment by sylvainbeo** [comment]
Ah. No i don't check that file.

**Comment by 3nids** [comment]
@sylvainbeo I am getting this error in Travis now
>   Restoring data-sample/qwat_v1.2.5_data_and_structure_sample.sql 
psql:data-sample/qwat_v1.2.5_data_and_structure_sample.sql:12: ERROR:  unrecognized configuration parameter "idle_in_transaction_session_timeout"

Is it due to a wrong PG version on Travis? Shall I go up to 9.5?

**Comment by sylvainbeo** [comment]
@3nids No, it's due to a bad version of the qwat_v1.2.5_data_and_structure_sample.sql file. @haubourg is goind to fix the file, and relaunch the PR. I should be ok then, and new xxx_v1.2.6_xxx files should be produced in the data-sample repo.

**Comment by haubourg** [comment]
@sylvainbeo would that work also if I publish a 1.2.6 version instead of fixing 1.2.5?

**Comment by haubourg** [comment]
@sylvainbeo I pushed fixed a 1.2.6 sql dump. Restore works but there seem now that travis tries to apply the 1.2.6 update to a 1.2.6 database. Any idea?

````
Getting num version from qwat_demo
 1.2.6
Applying deltas on qwat_demo
    Bypassing  delta_1.0.0_12092016.sql, num version = 1.0.0
    Bypassing  delta_1.0.1_06062016.sql, num version = 1.0.1
    Bypassing  delta_1.1.0.sql, num version = 1.1.0
    Bypassing  delta_1.1.1_26012017.sql, num version = 1.1.1
    Bypassing  delta_1.2.0.sql, num version = 1.2.0
    Bypassing  delta_1.2.1_allow_installation_type_change.sql, num version = 1.2.1
    Bypassing  delta_1.2.2_new_audit_system.sql, num version = 1.2.2
    Bypassing  delta_1.2.3_printmap_add_scale_field.sql, num version = 1.2.3
    Bypassing  delta_1.2.4_references_delete_cascade.sql, num version = 1.2.4
    Bypassing  delta_1.2.5_fix_part_inheritance.sql, num version = 1.2.5
    Processing delta_1.2.6_fix_audited_tables_and_views.sql, num version = 1 (1.2.6)
psql:/home/travis/build/qwat/qwat-data-model/update/delta/delta_1.2.6_fix_audited_tables_and_views.sql:17: ERROR:  duplicate key value violates unique constraint "logged_relations_pkey"
DETAIL:  Key (relation_name, uid_column)=(qwat_od.distributor, id) already exists.
CONTEXT:  SQL statement "insert into qwat_sys.logged_relations (relation_name, uid_column)
         select target_table, a.attname
           from pg_index i
           join pg_attribute a on a.attrelid = i.indrelid
                              and a.attnum = any(i.indkey)
          where i.indrelid = target_table::regclass
            and i.indisprimary"
PL/pgSQL function qwat_sys.audit_table(regclass,boolean,boolean,text[]) line 32 at SQL statement
SQL statement "SELECT qwat_sys.audit_table('qwat_od.distributor')"
PL/pgSQL function inline_code_block line 4 at PERFORM
The command "$TRAVIS_BUILD_DIR/update/verify_upgrade_db.sh" exited with 3.
Done. Your build exited with 1.
````

**Comment by sylvainbeo** [comment]
@haubourg And you're sure that what you've done in the 1.2.6 delta is correct ?

**Comment by sylvainbeo** [comment]
@haubourg I'm trying tosolve this problem.

**Comment by sylvainbeo** [comment]
Problem solved. But now, the token we used is no longer valid. Trying to create a new one.

**Comment by haubourg** [comment]
Hi, Travis complains about a qwat_demo service definition missing. 
Any idea @sylvainbeo ?
` psql: definition of service "qwat_demo" not found`

**Comment by sylvainbeo** [comment]
That's new. I check that.

**Comment by sylvainbeo** [comment]
Ok found. It's because the travis config must include a new DB definition. Which is present in the master and not in your branch. I add it.

**Comment by sylvainbeo** [comment]
Back to the original problem: authentification is not working anymore since github send us a message saying that they were deleting our tokens.

**Comment by 3nids** [comment]
do you have any news here? can I do something?

**Comment by sylvainbeo** [comment]
@3nids Authent does not work for pushing new DUMP atthe end of the process. Don't know why. It was working until Github remove the tokens. I've re-created it, but no luck. Yes you can have a look to see if there is something i don't see. Thank you.

**Comment by 3nids** [comment]
merging as it is quite safe and tested.

**Pull request merged**
