### PR TITLE
cover diameter -> form_dimension & added polygon geom & fixed geom inserts

### PR DESCRIPTION
**Pull request by tudorbarascu**
See https://github.com/qwat/qwat-data-model/issues/80

### CODE REVIEW

**Comment by tudorbarascu** [comment]
I couldn't add covers due to your last commits as I was getting the ``ERROR:  Column has Z dimension but geometry does not`` problem.

While fixing it and studying the last functions, I noticed that for nodes, the 3d geom was not always in sync with the altitude value.
I wrote some quick inserts that should go into a future travis test.
As I didn't had the time over the weekend, I only fixed the cover part in the latest commit.

```
INSERT INTO qwat_od.distributor (name) SELECT 'Test Distributor';
-- 1      2d geom with altitude 200
INSERT INTO qwat_od.vw_element_installation (altitude, geometry, fk_distributor, installation_type, fk_status, fk_precision, fk_precisionalti, fk_watertype, fk_object_reference)
VALUES (200, ST_SetSRID( ST_MakePoint( 400000, 400000), 21781), 1, 'chamber', 101, 101, 101, 101, 101);
-- 2      2d geom with altitude NULL
INSERT INTO qwat_od.vw_element_installation (altitude, geometry, fk_distributor, installation_type, fk_status, fk_precision, fk_precisionalti, fk_watertype, fk_object_reference)
VALUES (NULL, ST_SetSRID( ST_MakePoint( 400001, 400001), 21781), 1, 'chamber', 101, 101, 101, 101, 101);
-- 3      3d geom (z = 201) without separate altitude
INSERT INTO qwat_od.vw_element_installation (altitude, geometry, fk_distributor, installation_type, fk_status, fk_precision, fk_precisionalti, fk_watertype, fk_object_reference)
VALUES (NULL, ST_SetSRID( ST_MakePoint( 400002, 400002, 201), 21781), 1, 'chamber', 101, 101, 101, 101, 101);
-- 4      3d geom (z = 500) with different altitude (202)
INSERT INTO qwat_od.vw_element_installation (altitude, geometry, fk_distributor, installation_type, fk_status, fk_precision, fk_precisionalti, fk_watertype, fk_object_reference)
VALUES (202, ST_SetSRID( ST_MakePoint( 400003, 400003, 500), 21781), 1, 'chamber', 101, 101, 101, 101, 101);

SELECT ST_z(geometry) FROM qwat_od.node;

-- 5      cover with 200 altitude
insert into qwat_od.cover
(altitude, fk_distributor, fk_installation, fk_status, geometry)
SELECT 200, 1, 2, 101, ST_SetSRID( ST_MakePoint( 400000, 400000), 21781);

-- 6      cover without altitude or 3d geom
insert into qwat_od.cover
(fk_distributor, fk_installation, fk_status, geometry)
SELECT 1, 1, 101, ST_SetSRID( ST_MakePoint( 400001, 400001), 21781);

-- 7      cover with 3d geom (z = 201)
insert into qwat_od.cover
(fk_distributor, fk_installation, fk_status, geometry)
SELECT 1, 1, 101, ST_SetSRID( ST_MakePoint( 400002, 400002, 201), 21781);

-- 8     3d geom (z = 500) with different altitude (202)
insert into qwat_od.cover
(altitude, fk_distributor, fk_installation, fk_status, geometry)
SELECT 202, 1, 1, 101, ST_SetSRID( ST_MakePoint( 400003, 400003, 500), 21781);

SELECT St_z(geometry), altitude FROM qwat_od.cover;
```

**Comment by tudorbarascu** [comment]
I've rebased according to your latest commits.

**Comment by tudorbarascu** [comment]
The https://github.com/qwat/qwat-data-model/commit/473bc0c081dcedde8006df53d6e12078703010ed commit fixes 3 of the INSERTS on cover.
The following one still doesn't work due to the ``ft_geom3d_altitude`` function:
```
insert into qwat_od.cover
(fk_distributor, fk_installation, fk_status, geometry)
SELECT 1, 1, 101, ST_SetSRID( ST_MakePoint( 400001, 400001), 21781);
```
as it outputs:
``ERROR:  new row for relation "cover" violates check constraint "enforce_dims_geometry"``

**Comment by 3nids** [comment]
thanks a lot

**Pull request merged**
