### PR TITLE
WIP: Make changes for Pum 0.6

### PR DESCRIPTION
**Pull request by elemoine**
In Pum 0.6 (and higher) the version flag was changed for `-v` to `-V`. This PR accomodates for this change.

Also, there's a regression in Pum 0.6. See https://github.com/opengisch/pum/pull/38. Commit f3e233c tests that the fix for the regression does work for QWAT. I'll remove that commit when there's a new Pum release on pypi.

### CODE REVIEW

**Comment by elemoine** [comment]
Ok, https://github.com/opengisch/pum/pull/38 fixes the problems. Let's wait for a new Pum release before merging this.

**Comment by 3nids** [comment]
@elemoine would you prefer me to revert the -v/-V change or we keep the new one?

**Comment by elemoine** [comment]
> @elemoine would you prefer me to revert the -v/-V change or we keep the new one?

Yes, that would make sense to me. I think `-v` is more natural.

**Comment by lbartoletti** [comment]
@elemoine Do you think this can be fixed and integrated into 1.3.3?

**Comment by elemoine** [comment]
I've just checked with Pum 0.7.1 (the latest version), and `pum -v` (lower-case `v`) does output the version again. So this PR can just be closed.

**Pull request closed without merging**
