### PR TITLE
Add service arg everywhere

### PR DESCRIPTION
**Pull request by lbartoletti**
A service is required and it's explicit with this command.
This adds security in case when the service is not found/exported. (I found one case, that I need to investigate).

### CODE REVIEW

**Comment by elemoine** [comment]
Do you also want to remove the `export PGSERVICE` statements from `init_qwat.sh`, `tests.sh`, `tests_scalability.sh` and `tests_scalability_multithread.sh`?

**Comment by elemoine** [comment]
Just one comment, otherwise +1 with making this explicit.

**Comment by lbartoletti** [comment]
yak shaving was near :)

**Comment by haubourg** [comment]
Ready for merge ?

**Comment by lbartoletti** [comment]
Yes

**Comment by elemoine** [comment]
I just tested `init_qwat.sh` with your patch applied. Both

```shell
$ ./init_qwat.sh -p qwat -s 21781 -d -r
```

and

```shell
$ PGSERVICE=qwat ./init_qwat.sh -s 21781 -d -r
```

worked perfectly.

Now I did not bother run all the other scripts.

Good to merge to me. Thanks @lbartoletti.

**Pull request merged**
