### PR TITLE
[fix qwat/QWAT/#174] on delete cascade for subscriber and meter refer…

### PR DESCRIPTION
**Pull request by 3nids**
…ences, on delete set null for pipe.fk_parent

### CODE REVIEW

**Comment by 3nids** [comment]
see qwat/QWAT/#174

**Comment by 3nids** [comment]
@sylvainbeo would need a bit of help here too.

I am trying to change constraint actions. 

image

Any idea?

**Comment by sylvainbeo** [comment]
Again, sounds like a bad ORDER in the check SQL.

Please edit you test_migration.sql,

Line 104 is : ORDER BY p.relname, t.tgname
Replace with : ORDER BY p.relname, t.tgname, pp.prosrc

Commit and push.

**Comment by 3nids** [comment]
will try on monday thanks for the feedback.

**Comment by 3nids** [comment]
@sylvainbeo apparently it doesn't solve the issue

**Comment by sylvainbeo** [comment]
@3nids Seems fixed now.

**Comment by 3nids** [comment]
@sylvainbeo perfect, thanks a lot!

**Pull request merged**
