### PR TITLE
Update sire extension

### PR DESCRIPTION
**Pull request by kandre**
[WIP] This PR fixes model changes from older SIRE versions to SIRE 5.0.
https://www.vd.ch/fileadmin/user_upload/organisation/dse/scav/sire/Diff_mod%C3%A8le_4.8_5.0.xlsx

More fixes related to the code itself (and not the SIRE udpates) will come.

### CODE REVIEW

**Comment by haubourg** [comment]
Hi @kandre , 

I see some minor warnings  in the travis log, 

```
psql:/home/travis/build/qwat/qwat-data-model/extensions/ch_vd_sire/views/vanne_clapet.sql:44: WARNING:  column "id_distributeur_2" has type "unknown"
DETAIL:  Proceeding with relation creation anyway.
psql:/home/travis/build/qwat/qwat-data-model/extensions/ch_vd_sire/views/vanne_clapet.sql:44: WARNING:  column "id_zone_pression_2" has type "unknown"
DETAIL:  Proceeding with relation creation anyway.

```

I think `id_distributeur_2` should be explicitly typed

**Comment by haubourg** [comment]
@lbartoletti 
we have one strange error in travis here:

```

[.snip.]

Message from RecreateViews: Recreating ch_vd_sire views: done
OK
     Applying post-all.py... Message from RecreateViews: Recreating sigip views
Message from RecreateViews: PGSERVICE=qwat_prod SRID=21781 /home/travis/build/qwat/qwat-data-model/.build/customizations/sigip/delta/../rewrite_views.sh
SET

[.snip.]

CREATE SCHEMA
SET
psql:/home/travis/build/qwat/qwat-data-model/.build/customizations/sigip/damage/damage.sql:26: ERROR:  relation "damage" already exists
Message from RecreateViews: Recreating sigip views: done
```

I think this is the fake customisation scenario we added in travis 

Maybe this line https://github.com/qwat/qwat-data-model/blob/7179cae7864773f28c61e060bf36295af0bc57ed/.build/customizations/sigip/damage/damage.sql#L1 should be a `CREATE IF NOT EXISTS` ?

**Comment by kandre** [comment]
Do you want me to fix CREATE TABLE qwat_od.damage error in this PR ?

**Comment by haubourg** [comment]
@kandre nope, this should be a separe PR, and I think @lbartoletti  can handle this. Thanks!

**Comment by kandre** [comment]
@lbartoletti yes it can be merged, I'll make few more changes to the next release

**Comment by lbartoletti** [comment]
target for release 1.3.3 #250

**Pull request merged**
