### PR TITLE
Audit triggers on views

### PR DESCRIPTION
**Pull request by sylvainbeo**
Moved audit triggers on views

### CODE REVIEW

**Comment by 3nids** [comment]
good job, would be nice to PR upstreamn https://github.com/2ndQuadrant/audit-trigger

**Comment by haubourg** [comment]
Hi Sylvain,
we have conflict here, can you solve that so that this can be merged and closed? Thanks
Régis

**Comment by haubourg** [comment]
@sylvainbeo testing that on another database, I get an error when doing

> SELECT api_maj.audit_view('maj_plan.troncon');

Error is that Views cannot have TRUNCATE trigger. Any idea?

```
NOTICE:  trigger "audit_trigger_row" for relation "maj_plan.troncon" does not exist, skipping
CONTEXT:  SQL statement "DROP TRIGGER IF EXISTS audit_trigger_row ON maj_plan.troncon"
PL/pgSQL function api_maj.audit_view(regclass,boolean,text[]) line 6 at EXECUTE
NOTICE:  trigger "audit_trigger_stm" for relation "maj_plan.troncon" does not exist, skipping
CONTEXT:  SQL statement "DROP TRIGGER IF EXISTS audit_trigger_stm ON maj_plan.troncon"
PL/pgSQL function api_maj.audit_view(regclass,boolean,text[]) line 7 at EXECUTE
NOTICE:  CREATE TRIGGER audit_trigger_stm AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON maj_plan.troncon FOR EACH STATEMENT EXECUTE PROCEDURE api_maj.if_modified_func('true');


ERROR:  "troncon" is a view
DETAIL:  Views cannot have TRUNCATE triggers.
CONTEXT:  SQL statement "CREATE TRIGGER audit_trigger_stm AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON maj_plan.troncon FOR EACH STATEMENT EXECUTE PROCEDURE api_maj.if_modified_func('true');"
PL/pgSQL function api_maj.audit_view(regclass,boolean,text[]) line 14 at EXECUTE

********** Erreur **********

ERROR: "troncon" is a view
État SQL :42809
Détail :Views cannot have TRUNCATE triggers.
Contexte : SQL statement "CREATE TRIGGER audit_trigger_stm AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON maj_plan.troncon FOR EACH STATEMENT EXECUTE PROCEDURE api_maj.if_modified_func('true');"
PL/pgSQL function api_maj.audit_view(regclass,boolean,text[]) line 14 at EXECUTE

NOTICE:  trigger "audit_trigger_row" for relation "maj_plan.troncon" does not exist, skipping
CONTEXT:  SQL statement "DROP TRIGGER IF EXISTS audit_trigger_row ON maj_plan.troncon"
PL/pgSQL function api_maj.audit_view(regclass,boolean,text[]) line 6 at EXECUTE
NOTICE:  trigger "audit_trigger_stm" for relation "maj_plan.troncon" does not exist, skipping
CONTEXT:  SQL statement "DROP TRIGGER IF EXISTS audit_trigger_stm ON maj_plan.troncon"
PL/pgSQL function api_maj.audit_view(regclass,boolean,text[]) line 7 at EXECUTE
NOTICE:  CREATE TRIGGER audit_trigger_stm AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON maj_plan.troncon FOR EACH STATEMENT EXECUTE PROCEDURE api_maj.if_modified_func('true');


ERROR:  "troncon" is a view
DETAIL:  Views cannot have TRUNCATE triggers.
CONTEXT:  SQL statement "CREATE TRIGGER audit_trigger_stm AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON maj_plan.troncon FOR EACH STATEMENT EXECUTE PROCEDURE api_maj.if_modified_func('true');"
PL/pgSQL function api_maj.audit_view(regclass,boolean,text[]) line 14 at EXECUTE

********** Erreur **********

ERROR: "troncon" is a view
État SQL :42809
Détail :Views cannot have TRUNCATE triggers.
Contexte : SQL statement "CREATE TRIGGER audit_trigger_stm AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON maj_plan.troncon FOR EACH STATEMENT EXECUTE PROCEDURE api_maj.if_modified_func('true');"
PL/pgSQL function api_maj.audit_view(regclass,boolean,text[]) line 14 at EXECUTE
```

**Comment by haubourg** [comment]
suppressing the "OR DELETE' part stm_targets seems to work here

**Comment by haubourg** [comment]
Testing the audit triggers based on that code does not fill row_data and changed_fields hstores in logged_action table. This breaks @mhugo history viewer plugin since old and new attributes are empty

I tested in two other databases, using different schemas for audit functions and tables. I made a diff between 2nd quadrant sources and qwat's and found only one minor difference. restoring 2nd quadrant version didn't help. 

@sylvainbeo @3nids can you confirm ?

**Comment by haubourg** [comment]
PR submitted upstream https://github.com/2ndQuadrant/audit-trigger/pull/26
Now let's make a PR for QWAT.

**Comment by haubourg** [comment]
closing, new PR replacing

**Pull request closed without merging**
