### PR TITLE
Add History audi new generation for views 

### PR DESCRIPTION
**Pull request by haubourg**
forwards @sylvainbeo PR from 17 jan

### CODE REVIEW

**Comment by 3nids** [comment]
any news regarding merging upstream (2nd-quadrant) ?

**Comment by haubourg** [comment]
None unfortunately. I have had some questions from qgis users and current situation is not good. We'll have to fork I'm afraid.

**Comment by sylvainbeo** [comment]
Ok. This is solved on my fork :

https://travis-ci.org/sylvainbeo/qwat-data-model/builds/213427065

The problem was a missing order by in the test_migration.sql for multiple column primary keys.

**Comment by haubourg** [comment]
@3nids, at last, it passes the tests. You can rebuild also your PR #156. 
I didn't change version number yet. I let you choose and merge both.

**Comment by 3nids** [comment]
glad to see this merge, great work.
would be better to rebase before merging, it makes the changelog much more readable.

**Comment by haubourg** [comment]
@3nids  sorry for the mess, Tag 1.2.2 an release are now done.

**Pull request merged**
