### PR TITLE
Deploy demodata automatically from travis

### PR DESCRIPTION
**Pull request by m-kuhn**
A.k.a. "continuous deployment"

* Deployment happens only if all tests including pum succeed
* Deployment uploads to a new release
* The release name is the name of the current git tag
* Four dumps are uploaded (sql and custom)
* Travis output has been cleaned up

Pum is now installed using pip from pypi, the submodule has been removed.

This should only be merged, once we have a clean migration path with a green travis.

You can find a sample on what the new download page looks like here: https://github.com/m-kuhn/qwat-data-model/releases/tag/9.9

### CODE REVIEW

**Comment by haubourg** [comment]
Nice! mid november is already there :)
python 3 seems to fail in initializing QWAT. Old Travis scripts are using python 2.7.
 @3nids  @sylvainbeo any opinion if porting python scripts to python3 is the best option?

**Comment by sylvainbeo** [comment]
No opinion for me right now, i'm not experimented with python 3.

**Comment by m-kuhn** [comment]
Let's see if it's only some trivial `print`s and stuff

**Comment by m-kuhn** [comment]
Migration scripts should work portable now (python2 or python3)

metaproject seems to be missing a patch though
https://travis-ci.org/qwat/qwat-data-model/builds/290391405#L2263-L2270

**Comment by m-kuhn** [comment]
The code it seems to fail on in metaproject is not clear to me:

https://github.com/opengisch/metaproject/commit/6f0bb1abbbddfe2d72302d52b68fab77ec3aa527#commitcomment-25094829

**Comment by m-kuhn** [comment]
And here's the error:

> UnboundLocalError: local variable 'child' referenced before assignment

https://travis-ci.org/qwat/qwat-data-model/builds/290391405#L2672

**Comment by 3nids** [comment]
@m-kuhn @sylvainbeo I think the error was a bit further. Can you try with https://github.com/opengisch/metaproject/pull/6

**Comment by m-kuhn** [comment]
Thanks @3nids 


@sylvainbeo feel free to merge if this deblocks you :+1:

**Comment by sylvainbeo** [comment]
Indeed that was easy :)

**Pull request merged**
