### PR TITLE
remove FALSE default for hydrant underground and marked

### PR DESCRIPTION
**Pull request by tudorbarascu**
The hydrant ``underground`` and ``marked`` columns are currently ``NOT NULL`` and with False as default.
Now that I look at them it doesn't feel right to have them default to anything as we should leave this to the user/editors to fill the possibilities.
I prefer NULL values instead of automatically filled ones that come with the uncertainty whether the editor actually chose the value or not.

Thoughts?

### CODE REVIEW

**Comment by 3nids** [comment]
Well, in practice about 99.50% of them are not underground, so I feel it's more practical.
Although this could be done on the client side, as it would let the administrator decide the default value.

So +0 on my side.

**Comment by tudorbarascu** [comment]
@3nids Thanks for your thoughts.
Indeed, I was thinking of leaving this in the hands of the administrator, client side.
If we're going to use a default on the database side I guess we should document this so that normal users aren't baffled about the automatic filling database side.

Any opinions about the ``marked`` part?

**Comment by 3nids** [comment]
same, ok for me to merge.
@haubourg any objection to merge?

**Comment by haubourg** [comment]
From a user point of view, I have no strong opinion on that.
From release management, we need to build a SQL patch in update with each commit, if we don't do so, it's going to be hard to reconstruct one later, and Travis tests won't work (when fixed).

**Comment by tudorbarascu** [comment]
@haubourg  I was waiting for #179 to know the model number in the delta.

**Comment by lbartoletti** [comment]
@tudorbarascu can you update your PR for next release, please?

**Comment by tudorbarascu** [comment]
@lbartoletti This can be merged

**Comment by lbartoletti** [comment]
Thanks @tudorbarascu !

**Comment by lbartoletti** [comment]
target for release 1.3.3 #250

**Pull request merged**
