### PR TITLE
add fk_precision, fk_precisionalti and fk_object_reference to cover

### PR DESCRIPTION
**Pull request by tudorbarascu**
See #80 

I'll make the delta file after the CI is working again.

### CODE REVIEW

**Comment by lbartoletti** [comment]
@tudorbarascu can you update your PR for next release, please?

@ponceta @kandre thought?

**Comment by tudorbarascu** [comment]
@lbartoletti I updated the PR. These columns were lost when the covers weren't considered nodes anymore. Now they're back. In the delta file I added a default ``103`` "To be determined" value for ``fk_precision`` and then dropped it afterwards as the fk_precision column should be NOT NULL.

**Comment by tudorbarascu** [comment]
@lbartoletti Can be merged now IMHO. Travis was complaining as I had a ``-`` almost at the end of the delta file and it ignored it.

**Comment by tudorbarascu** [comment]
Is there any reason not to merge this? IMHO it's a regression as we lost these columns.

**Comment by lbartoletti** [comment]
target for release 1.3.3 #250

**Comment by lbartoletti** [comment]
Thanks @tudorbarascu

**Comment by ponceta** [comment]
@tudorbarascu Sorry for latency! Thanks for these!

I've encountered a small bug with the deltas : 

https://github.com/qwat/qwat-data-model/pull/188/files#diff-014985b371786bb83041e7b4f3b80075R15

If you have altitude on existing cover data, these will fail since `fk_precisionalti` and `fk_object_reference` will be NULL.

```
ALTER TABLE qwat_od.cover ADD CONSTRAINT chk_cover_altitude_obj_ref CHECK (fk_object_reference IS NOT NULL OR altitude IS NULL );
ALTER TABLE qwat_od.cover ADD CONSTRAINT chk_cover_altitude_precisionalti CHECK (fk_precisionalti IS NOT NULL OR altitude IS NULL );
```

**Comment by tudorbarascu** [comment]
@ponceta Hmm.. indeed. Then somewhat of an .." update all covers that have altitude and set their fk_obj_ref and fk_precisonalti to TO BE DETERMINED" should be the solution, right?

**Pull request merged**
