### PR TITLE
Pum integration2

### PR DESCRIPTION
**Pull request by sylvainbeo**
@m-kuhn @haubourg Hi, have a look to this PR. I've added pre and post-all delta file + a pre for 1.2.8. 

Please comment.

### CODE REVIEW

**Comment by 3nids** [comment]
is that a green light ????
haven't seen one for quite a while around here...
good job to all of you!!!

**Comment by m-kuhn** [comment]
Great stuff, that's good to see.

@marioba any feedback from your side concerning the use of `os.system`? Alternatively there would be the `subprocess` module which could also intercept `stdout` and `stderr`, should that be sent back to Pum, and of course `psycopg`. Not sure how you envisioned this.

**Comment by marioba** [comment]
👍for the green light...
 
In the `DeltaPy` abstract class, there is the `write_message` method designed to write the subclass outputs. Currently, the method doesn't make much more than a simple `print()` but I think it would be good to have a centralized output so, if we want to manage it differently in the future, it's easy to modify it. 
And maybe it would be also a good idea to define some exception types that the subclasses can raise in the `run` method...

**Comment by m-kuhn** [comment]
Thinking about this again, it might be nice to send all sql through psycopg2. At least from a transaction perspective it would be nice to send everything through the same interface and have total control to commit or rollback.

**Comment by sylvainbeo** [comment]
Ok all, we wait for @haubourg  to have a look, and we merge.

**Comment by ponceta** [comment]
Thanks for the good work, this will be great to have this!

There's a small error here :

https://travis-ci.org/qwat/qwat-data-model/builds/293131379#L2870

Probably linked to SRID not beeing initialized somehow?

Il like the green tick but having errors and still been green can be a false positive for me.

The auth token is not working too?

**Comment by sylvainbeo** [comment]
@ponceta Ah oups. did not see this one, because travis was collapsing the lines. Yes indeed, it is because of the missing SRID. I have a look.

**Comment by m-kuhn** [comment]
Can someone check if the `GH_TOKEN` has the `public_repo` access set?

**Comment by m-kuhn** [comment]
@sylvainbeo I guess you need to check the return value of the `psql` call.

**Comment by sylvainbeo** [comment]
@m-kuhn The problem is on the post-all process. No sql is launched directly, just .sh 
I have a look.

**Comment by sylvainbeo** [comment]
SRID problem seems to be solved. 

Now i see another one  'schema "qwat_od" does not exist'

**Comment by sylvainbeo** [comment]
+ @m-kuhn 

> Traceback (most recent call last):
  File "./.deploy/create_release.py", line 154, in <module>
    main()
  File "./.deploy/create_release.py", line 144, in main
    url='{release_url}?name={filename}'.format(release_url=release['upload_url'][:-13], filename=filename)
KeyError: 'upload_url'

**Comment by m-kuhn** [comment]
@sylvainbeo , that normally happens when there's something broken with the api token

> Can someone check if the GH_TOKEN has the public_repo permission set?

**Comment by m-kuhn** [comment]
That should help: https://github.com/qwat/qwat-data-model/pull/206

**Comment by sylvainbeo** [comment]
I'm not a GH_TOKEN expert. here is the configuration for the tken (qwat_admin user)

image

**Comment by m-kuhn** [comment]
Looks good I think

**Comment by m-kuhn** [comment]
Ah wait... Actually deploy should only happen on tags...

**Comment by sylvainbeo** [comment]
@m-kuhn Indeed no tag.

**Comment by sylvainbeo** [comment]
Anyone has an idea on " schema "qwat_od" does not exist"..very weird.

**Comment by sylvainbeo** [comment]
mmmm... i have one. Maybe the .sh scripts are not launched on the right DATABASE.

**Comment by sylvainbeo** [comment]
Fixed !

**Comment by sylvainbeo** [comment]
Question: in the post-all.py file, i specify qwat_test as the output DB... maybe this should be a param.

**Comment by haubourg** [comment]
Merging that at last!

**Comment by m-kuhn** [comment]
:tada:

**Pull request merged**
