### PR TITLE
Pipe vertex modification for multithreads tests

### PR DESCRIPTION
**Pull request by sylvainbeo**

### CODE REVIEW

**Comment by haubourg** [comment]
What's the status here? Failing tests seem to be related to missing sql file in /delta directory. 
Since then on delta file has been added. How can we run again travis anfd go for a merge?

**Comment by sylvainbeo** [comment]
Status here is that branch is not needed anymore ,since we removed the valves from the nodes. Let's keep it for the moment, until model is fully validated.

**Comment by haubourg** [comment]
@sylvainbeo can we close that?

**Comment by sylvainbeo** [comment]
Yes we can.

**Comment by haubourg** [comment]
@sylvainbeo OK, let's make QWAT great again then (sorry couldn't help  ) and close that :+1:

**Pull request closed without merging**
