### PR TITLE
Set fk_object_reference and fk_precisionalti "TO BE DETERMINED" for covers with existing altitude

### PR DESCRIPTION
**Pull request by tudorbarascu**
Follow-up to #188

@ponceta I think this should cover the small issue, right?

### CODE REVIEW

**Comment by lbartoletti** [comment]
@ponceta @tudorbarascu OK to merge?

**Comment by tudorbarascu** [comment]
From me, yes!

**Comment by lbartoletti** [comment]
Thanks @tudorbarascu

**Comment by tudorbarascu** [comment]
@lbartoletti Thank you!

**Pull request merged**
