### PR TITLE
Building trigger in one shot (no more hierarchy)

### PR DESCRIPTION
**Pull request by sylvainbeo**

### CODE REVIEW

**Comment by 3nids** [comment]
views are not renamed (i.e. no need for new version?)

**Comment by sylvainbeo** [comment]
Sorry did not see your message. Which views  ?

**Comment by 3nids** [comment]
I mean shall we see this as a model update and provide a dummy delta (with just the model increment) ? How do you see it?

**Comment by sylvainbeo** [comment]
Ah. That's a good question.
Maybe it's best to add indeed an empty delta. At least to indicate it's a new version of the model. I do it.

**Comment by 3nids** [comment]
remove the local script?

**Comment by sylvainbeo** [comment]
Ok travis is fine with the metaproject (master).

**Comment by sylvainbeo** [comment]
The qwat-data-model needs to be updated to have the metaproject Master in sub repository.

**Comment by 3nids** [comment]
what do you mean? if you checkout to the proper commit in this branch (lvl_triggers_recursive), then master will be automatically updated when this PR is merged.
Am I missing something?

**Comment by sylvainbeo** [comment]
Ok. I'm not very familiar with sub-git dependencies vs PR. Anyway, if that's not the case, it wil be easy to do it afterwards.

**Pull request merged**
