### PR TITLE
Set pipe year check >= 1800 instead > 1800 and add some verbosity in init_qwat.sh

### PR DESCRIPTION
**Pull request by nicolas-sitylb**
- [x] [Set >= 1800 for pipe_year_check to accommodate the common usage of year 1800 for old pipes in survey offices.](https://github.com/qwat/qwat-data-model/commit/2af72989568e2ed204924698808bc04a73a5f17d). 
--> Resolve: https://github.com/qwat/qwat-data-model/issues/367
- [x] [Add some verbosity in init_qwat.sh.](https://github.com/qwat/qwat-data-model/commit/7bb27ff8f0a3d49b9bc3280bb643302e469501c6)
- [x] [Fix line return in insert_views.sh.](https://github.com/qwat/qwat-data-model/commit/d79cba8ac8dc62ec1b1fcec439a14c1d798f88d1)
- [x] Provide delta

### CODE REVIEW

**Comment by ponceta** [comment]
A delta is required with this code :
```
ALTER TABLE qwat_od.pipe ADD CONSTRAINT pipe_year_check CHECK (year IS NULL OR year >= 1800 AND (year <= EXTRACT(YEAR FROM NOW()) OR fk_status = 1306 AND year - 50 <= EXTRACT(YEAR FROM NOW())));
```

**Comment by olivierdalang** [comment]
Hmm `pum check` should have failed without the delta, no ?

**Comment by ponceta** [comment]
To my knowledge, pum check the existence but not the syntax of constraints.

**Comment by olivierdalang** [comment]
Ok, opened an issue here : https://github.com/opengisch/pum/issues/103

IMO worth looking into as there may be inconsistencies in constraints btw the datamodel and an upgraded datamodel, which could be serious in terms of data integrity

**Pull request merged**
