### PR TITLE
Fix Missing ELSE statement in installation_update and delete function…

### PR DESCRIPTION
**Pull request by lbartoletti**
…s #231

### CODE REVIEW

**Comment by sylvainbeo** [comment]
@lbartoletti These functions are self built. You should not update them in a delta.

**Comment by 3nids** [comment]
yes, fixes need to be done in metaproject.

**Comment by 3nids** [comment]
missing ELSE (are they strictly required?) would be in these sections:
https://github.com/opengisch/metaproject/blob/master/postgresql/pg_inheritance_view/pg_inheritance_view_recursive.py#L970-L976
https://github.com/opengisch/metaproject/blob/master/postgresql/pg_inheritance_view/pg_inheritance_view_recursive.py#L978-L1012
https://github.com/opengisch/metaproject/blob/master/postgresql/pg_inheritance_view/pg_inheritance_view_recursive.py#L1024-L1062
https://github.com/opengisch/metaproject/blob/master/postgresql/pg_inheritance_view/pg_inheritance_view_recursive.py#L1088-L1101

**Comment by lbartoletti** [comment]
@sylvainbeo @3nids Thanks.
Done in https://github.com/opengisch/metaproject/pull/7

**Comment by 3nids** [comment]
let's test this in model by upgrading metaproject?

**Pull request closed without merging**
