### PR TITLE
Steel materials

### PR DESCRIPTION
**Pull request by tudorbarascu**
Also, I think that the Steel/Acier pipe of 60 nominal diameter shouldn't exist in the pipe materials table as I couldn't find it in any standards. The equivalent that probably got that value written in the table is the Steel pipe of 50 nominal diameter that indeed has 60 as an approximate external diameter (so id 5258 should be replaced by 5257 for materials).
I think we should update the materials for pipe and delete it. Should I add this commit to this pull request?

All the best!

### CODE REVIEW

**Comment by tudorbarascu** [comment]
ping @3nids

**Comment by 3nids** [comment]
I'm on it!

**Comment by 3nids** [comment]
remove stell 60 in a6fb959e6f6a9ab744e3092b3d60bace6b9b362b

**Comment by 3nids** [comment]
thanks for the input!!!

**Pull request merged**
