### PR TITLE
More verbose error reporting on deploy failure

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by sylvainbeo** [comment]
Why are there some SIRE modifications on that PR  ?

**Comment by m-kuhn** [comment]
I based it on your branch to make the tests pass and actually launch deploy

**Comment by m-kuhn** [comment]
So, that's what we get:

```
Failed to create release!
Github API replied:
401 Unauthorized
{'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}
```

@sylvainbeo can you recreate the api token and delete / recreate it here: https://travis-ci.org/qwat/qwat-data-model/settings

**Comment by sylvainbeo** [comment]
@m-kuhn Done

**Comment by sylvainbeo** [comment]
Question: in the post-all.py file, i specify qwat_test as the output DB... maybe this should be a param.

**Comment by m-kuhn** [comment]
@sylvainbeo I changed it in the script to `GH_TOKEN` (not `OAUTH_TOKEN`) according to the name that was defined before. Should we stick to that?

**Comment by sylvainbeo** [comment]
@m-kuhn oh sorry. I change that

**Comment by sylvainbeo** [comment]
Fixed.

**Comment by m-kuhn** [comment]
Cool, seems to work https://github.com/qwat/qwat-data-model/releases/tag/test
Although the upload of demodata was interrupted, hopefully just a temporary issue.

**Comment by sylvainbeo** [comment]
Ok for me to merge.

**Comment by m-kuhn** [comment]
It's already merged, just checking what's going on with the git tag. It should already only deploy on tags, but apparently it also tries to deploy when no tag is set...

**Pull request closed without merging**
