### PR TITLE
fix incorrect nominal diameter value

### PR DESCRIPTION
**Pull request by kandre**
200mm nominal diameter values (value_en, value_fr, value_ro) were probably a copy paste from 150mm nominal diameter values.

### CODE REVIEW

**Comment by kandre** [comment]
@ponceta ready for merge/review

**Comment by ponceta** [comment]
A delta file is missing : 
 
delta_1.4.0_004_fix_incorrect_nominal_diameter_value.sql

with the update statement to fix this.

@kandre can you provide it?

**Comment by kandre** [comment]
Yes totally forgot it, will provide it soon

**Comment by kandre** [comment]
@ponceta here it is

**Comment by ponceta** [comment]
@kandre thank you for the fix and the delta

**Pull request merged**
