### PR TITLE
Fixed valve with handle view/demo distributor/removed node_altitude

### PR DESCRIPTION
**Pull request by tudorbarascu**
node_altitude values should go into altitude when migrating

### CODE REVIEW

**Comment by 3nids** [comment]
Thanks a lot. Please put the demo data in a distinct file and it'll be perfect !

**Comment by tudorbarascu** [comment]
Thanks also! I put the demo.sql in the ordinary_data dir. Hope it's ok.

**Comment by 3nids** [comment]
Perfect, you might want to add it to the init file too, with maybe an option similarly to the create roles option.
Otherwise I'll do it when I come back.

**Comment by tudorbarascu** [comment]
I'm busy now with migrating/testing everything, will do it afterwards ;).

**Pull request merged**
